import type { ConsoleItem } from '../../console-model'

export const ISSUE_SESSION: ConsoleItem = {
  id: 'sample:CW-2041',
  handle: 'CW-2041',
  triage: null,
  kind: 'error',
  repository: 'netko/api-gateway',
  scopeLabel: 'api-gateway',
  label: 'Critical error',
  severity: 'critical',
  age: '18m',
  title: 'TypeError: cannot read `sessionId` of undefined',
  subtitle: 'src/auth/session.ts:118 · resolveSession() · v4.18.2 · production',
  meta: '14,208 events · 3,104 users',
  events: '14,208',
  users: '3,104',
  badge: 'CRITICAL',
  badge2: 'REGRESSION',
  confidence: 'high confidence',
  read: 'Every failing call omits the ctx.session guard added in #4462. Two callsites still pass the old shape — webhooks/verify.ts and jobs/reindex.ts.',
  fixLabel: 'Open suggested fix',
  evidenceLabel: 'See the 2 callsites',
  trace: [
    {
      no: '118',
      current: true,
      text: 'at resolveSession (src/auth/session.ts:118:24)',
      tone: 'strong',
    },
    { no: '119', text: '  const id = ctx.session.sessionId;', tone: 'dim' },
    { no: '204', text: 'at verifyWebhook (src/webhooks/verify.ts:204:9)', tone: 'muted' },
    { no: '61', text: 'at handler (src/webhooks/route.ts:61:5)', tone: 'muted' },
    { no: '88', text: 'at runMiddleware (src/server/pipeline.ts:88:13)', tone: 'muted' },
    { no: '31', text: 'at reindexBatch (src/jobs/reindex.ts:31:7)', tone: 'muted' },
  ],
  crumbs: [
    {
      time: '09:40:58',
      kind: 'deploy',
      tone: 'info',
      message: 'v4.18.2 rolled out to 100% of production',
    },
    { time: '09:41:01', kind: 'http', tone: 'muted', message: 'POST /webhooks/stripe 200 (48ms)' },
    {
      time: '09:41:02',
      kind: 'auth',
      tone: 'muted',
      message: 'resolveSession(ctx) called without session',
    },
    {
      time: '09:41:02',
      kind: 'error',
      tone: 'bad',
      message: 'TypeError thrown, request failed 500',
    },
    {
      time: '09:41:03',
      kind: 'retry',
      tone: 'warn',
      message: 'webhook retried, failed identically',
    },
  ],
  logContext: [
    {
      time: '09:41:02.118',
      level: 'ERROR',
      message: "cannot read 'sessionId' of undefined req=7f21ac",
    },
    {
      time: '09:41:02.119',
      level: 'ERROR',
      message: 'verifyWebhook failed after 1 attempt status=500',
    },
    {
      time: '09:41:02.402',
      level: 'WARN',
      message: 'p95 latency 812ms exceeds 500ms region=eu-west-1',
    },
    { time: '09:41:02.771', level: 'INFO', message: 'session refreshed user=u_91042' },
    {
      time: '09:41:03.004',
      level: 'ERROR',
      message: "cannot read 'sessionId' of undefined req=7f21b0",
    },
    { time: '09:41:03.219', level: 'WARN', message: 'parseLegacyCursor() is deprecated' },
  ],
  tags: [
    { key: 'release', value: 'v4.18.2' },
    { key: 'environment', value: 'production' },
    { key: 'runtime', value: 'node 22.4.0' },
    { key: 'region', value: 'eu-west-1, us-east-1' },
    { key: 'handled', value: 'no' },
    { key: 'level', value: 'error' },
    { key: 'suspect commit', value: '#4462 · a1f09c2' },
    { key: 'url', value: '/webhooks/stripe' },
  ],
  fix: {
    title: 'Suggested fix',
    subtitle: 'Whiskers wrote this patch 2 minutes ago',
    note: 'Restores the guard at both callsites and keeps the old shape working for one release, so the webhook queue drains before you cut v4.19.',
    file: 'src/webhooks/verify.ts',
    cta: 'Open PR with this fix',
    hunk: [
      { no: '202', sign: '', text: 'export async function verifyWebhook(ctx) {' },
      { no: '203', sign: '-', text: '  const id = resolveSession(ctx).sessionId;' },
      { no: '203', sign: '+', text: '  const session = ctx.session ?? legacySession(ctx);' },
      { no: '204', sign: '+', text: '  if (!session) return reject(ctx, "no_session");' },
      { no: '205', sign: '+', text: '  const id = session.sessionId;' },
      { no: '206', sign: '', text: '  return sign(id, ctx.body);' },
    ],
    steps: [
      'apply the same guard in src/jobs/reindex.ts:31',
      'add a regression test for the missing-session path',
      'link the PR to CW-2041 and resolve on merge',
    ],
  },
}

export const ISSUE_BILLING: ConsoleItem = {
  id: 'sample:CW-2039',
  handle: 'CW-2039',
  triage: null,
  kind: 'error',
  repository: 'netko/api-gateway',
  scopeLabel: 'api-gateway',
  label: 'Error',
  severity: 'critical',
  age: '4h',
  title: 'TimeoutError: upstream billing service',
  subtitle: 'src/billing/client.ts:64 · charge() · v4.18.1 · production',
  meta: '2,840 events · 611 users',
  events: '2,840',
  users: '611',
  badge: 'ERROR',
  badge2: '',
  confidence: 'medium confidence',
  read: 'All failures are on the 5s default timeout against the billing vendor. Their status page reports degraded writes in eu-west-1 since 05:20.',
  fixLabel: 'Raise the timeout to 15s',
  evidenceLabel: 'Open vendor status',
  trace: [
    { no: '64', current: true, text: 'at charge (src/billing/client.ts:64:11)', tone: 'strong' },
    { no: '65', text: '  const res = await fetch(url, { timeout: 5000 });', tone: 'dim' },
    { no: '119', text: 'at renewSubscription (src/billing/renew.ts:119:5)', tone: 'muted' },
    { no: '44', text: 'at cron (src/jobs/renewals.ts:44:9)', tone: 'muted' },
  ],
  crumbs: [
    {
      time: '05:20:04',
      kind: 'vendor',
      tone: 'warn',
      message: 'billing vendor reports degraded writes',
    },
    {
      time: '05:21:10',
      kind: 'http',
      tone: 'muted',
      message: 'POST /charges timed out after 5000ms',
    },
    {
      time: '05:21:10',
      kind: 'error',
      tone: 'bad',
      message: 'TimeoutError surfaced to renewal job',
    },
  ],
  logContext: [
    {
      time: '05:21:10.004',
      level: 'ERROR',
      message: 'TimeoutError: upstream billing service after=5000ms',
    },
    { time: '05:21:10.118', level: 'WARN', message: 'renewal deferred subscription=sub_4410' },
    { time: '05:21:15.302', level: 'INFO', message: 'charge succeeded on retry amount=4900' },
  ],
  tags: [
    { key: 'release', value: 'v4.18.1' },
    { key: 'environment', value: 'production' },
    { key: 'vendor', value: 'billing-api' },
    { key: 'region', value: 'eu-west-1' },
    { key: 'handled', value: 'yes' },
    { key: 'level', value: 'error' },
  ],
  fix: {
    title: 'Suggested fix',
    subtitle: 'Vendor timeout, not our bug',
    note: 'Raises the timeout for renewal calls only and defers to the next cron window instead of failing the subscription.',
    file: 'src/billing/client.ts',
    cta: 'Open PR with this fix',
    hunk: [
      { no: '65', sign: '-', text: '  const res = await fetch(url, { timeout: 5000 });' },
      { no: '65', sign: '+', text: '  const res = await fetch(url, { timeout: 15000 });' },
      { no: '66', sign: '+', text: '  if (res.deferred) return scheduleNextWindow(ctx);' },
    ],
    steps: [
      'keep the 5s timeout for interactive checkout',
      'alert if deferrals exceed 100 in an hour',
    ],
  },
}

export const ISSUE_CURSOR: ConsoleItem = {
  id: 'sample:CW-2036',
  handle: 'CW-2036',
  triage: null,
  kind: 'error',
  repository: 'netko/api-gateway',
  scopeLabel: 'api-gateway',
  label: 'Resolved',
  severity: 'ok',
  age: '1d',
  title: 'RangeError in cursor paging',
  subtitle: 'src/db/cursor.ts:44 · pageAfter() · fixed in v4.18.2',
  meta: 'quiet for 6h',
  events: '0',
  users: '0',
  badge: 'RESOLVED',
  badge2: '',
  confidence: 'verified',
  read: 'Quiet for six hours across every region since v4.18.2 shipped. I will reopen this automatically if it fires again.',
  fixLabel: 'Reopen issue',
  evidenceLabel: 'Show the fix commit',
  trace: [
    { no: '44', current: true, text: 'at pageAfter (src/db/cursor.ts:44:19)', tone: 'strong' },
    { no: '45', text: '  return rows.slice(offset, offset + limit);', tone: 'dim' },
  ],
  crumbs: [
    {
      time: 'yesterday',
      kind: 'deploy',
      tone: 'info',
      message: 'v4.18.2 shipped with the cursor guard',
    },
    { time: '03:40', kind: 'verify', tone: 'ok', message: 'no events for 6h — auto-verified' },
  ],
  logContext: [{ time: '03:40:00.000', level: 'OK', message: 'CW-2036 verified quiet window=6h' }],
  tags: [
    { key: 'release', value: 'v4.18.2' },
    { key: 'resolved by', value: 'Mara Reyes' },
    { key: 'handled', value: 'yes' },
    { key: 'level', value: 'error' },
  ],
  fix: {
    title: 'Reopen CW-2036',
    subtitle: 'Only if you expect it back',
    note: 'Reopening restores the alert rule and re-subscribes the original owners.',
    file: 'CW-2036 · resolved in v4.18.2',
    cta: 'Reopen issue',
    hunk: [
      { no: '1', sign: '', text: 'resolved_in: v4.18.2' },
      { no: '2', sign: '', text: 'quiet_for: 6h 12m' },
    ],
    steps: ['re-subscribe Mara and the platform team'],
  },
}

export const ERROR_ITEMS = [ISSUE_SESSION, ISSUE_BILLING, ISSUE_CURSOR]
