import type { ConsoleItem } from '../../console-model'

export const ISSUE_SESSION: ConsoleItem = {
  id: 'sample:CW-2041',
  sourceId: 'sample-2041',
  handle: 'CW-2041',
  triage: null,
  kind: 'error',
  repository: 'netko/api-gateway',
  scopeLabel: 'api-gateway',
  label: 'Critical error',
  severity: 'critical',
  age: '18m',
  title: 'TypeError: cannot read `sessionId` of undefined',
  subtitle: 'src/auth/session.ts:118 · resolveSession() · v4.18.2 · production',
  meta: '14,208 events · 3,104 users',
  badge: 'CRITICAL',
  badge2: 'REGRESSION',
  confidence: 'high confidence',
  read: 'Every failing call omits the ctx.session guard added in #4462. Two callsites still pass the old shape — webhooks/verify.ts and jobs/reindex.ts.',
  fixLabel: 'Open suggested fix',
  evidenceLabel: 'See the 2 callsites',
  fix: {
    title: 'Suggested fix',
    subtitle: 'Whiskers wrote this patch 2 minutes ago',
    note: 'Restores the guard at both callsites and keeps the old shape working for one release, so the webhook queue drains before you cut v4.19.',
    file: 'src/webhooks/verify.ts',
    cta: 'Open PR with this fix',
    hunk: [
      { no: '202', sign: '', text: 'export async function verifyWebhook(ctx) {' },
      { no: '203', sign: '-', text: '  const id = resolveSession(ctx).sessionId;' },
      { no: '203', sign: '+', text: '  const session = ctx.session ?? legacySession(ctx);' },
      { no: '204', sign: '+', text: '  if (!session) return reject(ctx, "no_session");' },
      { no: '205', sign: '+', text: '  const id = session.sessionId;' },
      { no: '206', sign: '', text: '  return sign(id, ctx.body);' },
    ],
    steps: [
      'apply the same guard in src/jobs/reindex.ts:31',
      'add a regression test for the missing-session path',
      'link the PR to CW-2041 and resolve on merge',
    ],
  },
}

export const ISSUE_BILLING: ConsoleItem = {
  id: 'sample:CW-2039',
  sourceId: 'sample-2039',
  handle: 'CW-2039',
  triage: null,
  kind: 'error',
  repository: 'netko/api-gateway',
  scopeLabel: 'api-gateway',
  label: 'Error',
  severity: 'critical',
  age: '4h',
  title: 'TimeoutError: upstream billing service',
  subtitle: 'src/billing/client.ts:64 · charge() · v4.18.1 · production',
  meta: '2,840 events · 611 users',
  badge: 'ERROR',
  badge2: '',
  confidence: 'medium confidence',
  read: 'All failures are on the 5s default timeout against the billing vendor. Their status page reports degraded writes in eu-west-1 since 05:20.',
  fixLabel: 'Raise the timeout to 15s',
  evidenceLabel: 'Open vendor status',
  fix: {
    title: 'Suggested fix',
    subtitle: 'Vendor timeout, not our bug',
    note: 'Raises the timeout for renewal calls only and defers to the next cron window instead of failing the subscription.',
    file: 'src/billing/client.ts',
    cta: 'Open PR with this fix',
    hunk: [
      { no: '65', sign: '-', text: '  const res = await fetch(url, { timeout: 5000 });' },
      { no: '65', sign: '+', text: '  const res = await fetch(url, { timeout: 15000 });' },
      { no: '66', sign: '+', text: '  if (res.deferred) return scheduleNextWindow(ctx);' },
    ],
    steps: [
      'keep the 5s timeout for interactive checkout',
      'alert if deferrals exceed 100 in an hour',
    ],
  },
}

export const ISSUE_CURSOR: ConsoleItem = {
  id: 'sample:CW-2036',
  sourceId: 'sample-2036',
  handle: 'CW-2036',
  triage: null,
  kind: 'error',
  repository: 'netko/api-gateway',
  scopeLabel: 'api-gateway',
  label: 'Resolved',
  severity: 'ok',
  age: '1d',
  title: 'RangeError in cursor paging',
  subtitle: 'src/db/cursor.ts:44 · pageAfter() · fixed in v4.18.2',
  meta: 'quiet for 6h',
  badge: 'RESOLVED',
  badge2: '',
  confidence: 'verified',
  read: 'Quiet for six hours across every region since v4.18.2 shipped. I will reopen this automatically if it fires again.',
  fixLabel: 'Reopen issue',
  evidenceLabel: 'Show the fix commit',
  fix: {
    title: 'Reopen CW-2036',
    subtitle: 'Only if you expect it back',
    note: 'Reopening restores the alert rule and re-subscribes the original owners.',
    file: 'CW-2036 · resolved in v4.18.2',
    cta: 'Reopen issue',
    hunk: [
      { no: '1', sign: '', text: 'resolved_in: v4.18.2' },
      { no: '2', sign: '', text: 'quiet_for: 6h 12m' },
    ],
    steps: ['re-subscribe Mara and the platform team'],
  },
}

export const ERROR_ITEMS = [ISSUE_SESSION, ISSUE_BILLING, ISSUE_CURSOR]
