import type { ConsoleItem } from '../../console-model'

export const LOG_INGEST_LATENCY: ConsoleItem = {
  id: 'LOG-882',
  kind: 'log',
  label: 'Log alert',
  severity: 'warning',
  age: '1h',
  title: 'p95 latency above 800ms on /v2/ingest',
  subtitle: 'threshold 500ms · eu-west-1 · 5m rolling window',
  meta: 'eu-west-1 · threshold 500ms',
  badge: 'WARNING',
  badge2: '',
  confidence: 'watching',
  read: 'Latency tracks the session retries one-for-one — the same webhook traffic is arriving twice. This likely clears when CW-2041 is fixed.',
  fixLabel: 'Create issue from pattern',
  evidenceLabel: 'Correlate with CW-2041',
  metricLabel: 'p95 request duration',
  metricSub: '/v2/ingest · eu-west-1',
  metric: '812ms',
  metricDelta: '+62% vs 24h',
  matchCount: '18,440 lines',
  bars: [
    { percent: 30, hot: false },
    { percent: 34, hot: false },
    { percent: 28, hot: false },
    { percent: 36, hot: false },
    { percent: 32, hot: false },
    { percent: 40, hot: false },
    { percent: 38, hot: false },
    { percent: 44, hot: false },
    { percent: 42, hot: false },
    { percent: 52, hot: true },
    { percent: 58, hot: true },
    { percent: 54, hot: true },
    { percent: 66, hot: true },
    { percent: 62, hot: true },
    { percent: 70, hot: true },
    { percent: 68, hot: true },
    { percent: 78, hot: true },
    { percent: 74, hot: true },
    { percent: 82, hot: true },
    { percent: 88, hot: true },
    { percent: 84, hot: true },
    { percent: 94, hot: true },
    { percent: 100, hot: true },
    { percent: 96, hot: true },
  ],
  lines: [
    {
      time: '09:41:02.402',
      level: 'WARN',
      message: 'p95 latency 812ms exceeds 500ms region=eu-west-1',
    },
    { time: '09:41:02.905', level: 'WARN', message: 'ingest queue depth 4,120 (soft cap 2,000)' },
    { time: '09:41:03.410', level: 'INFO', message: 'POST /v2/ingest 202 bytes=18440 dur=844ms' },
    { time: '09:41:04.118', level: 'WARN', message: 'duplicate delivery id=7f21ac attempt=2' },
    { time: '09:41:04.551', level: 'WARN', message: 'retry storm detected attempts=940' },
    { time: '09:41:05.702', level: 'WARN', message: 'p95 latency 798ms region=eu-west-1' },
  ],
  fix: {
    title: 'Create issue from pattern',
    subtitle: 'Groups 18,440 matching lines into one tracked issue',
    note: 'Whiskers will open CW-2048, attach this query as the alert condition, and link it to CW-2041 as a likely cause.',
    file: 'alert · level:warn route:/v2/ingest',
    cta: 'Create CW-2048',
    hunk: [
      { no: '1', sign: '', text: 'level:warn service:http/ingest' },
      { no: '2', sign: '', text: '| where duration_p95 > 500ms' },
      { no: '3', sign: '+', text: '| group by route, region' },
      { no: '4', sign: '+', text: '| alert after 3 windows' },
    ],
    steps: [
      'notify #oncall-platform on the first breach',
      'auto-resolve when p95 holds under 500ms for 30m',
      'link to CW-2041 as suspected cause',
    ],
  },
}

export const LOG_DEPRECATIONS: ConsoleItem = {
  id: 'LOG-874',
  kind: 'log',
  label: 'Log pattern',
  severity: 'warning',
  age: '9h',
  title: 'Deprecation warnings spiking after v4.18.2',
  subtitle: '41 distinct callsites · all environments',
  meta: '18,440 lines · 41 callsites',
  badge: 'PATTERN',
  badge2: '',
  confidence: 'low urgency',
  read: 'One deprecated helper, parseLegacyCursor(), accounts for all 41 callsites. I can open a single PR that migrates every one of them.',
  fixLabel: 'Open the migration PR',
  evidenceLabel: 'List all callsites',
  metricLabel: 'Deprecation warnings',
  metricSub: 'parseLegacyCursor() · all envs',
  metric: '18,440',
  metricDelta: '+9x vs 24h',
  matchCount: '41 callsites',
  bars: [
    { percent: 8, hot: false },
    { percent: 10, hot: false },
    { percent: 9, hot: false },
    { percent: 12, hot: false },
    { percent: 11, hot: false },
    { percent: 14, hot: false },
    { percent: 18, hot: false },
    { percent: 22, hot: false },
    { percent: 30, hot: true },
    { percent: 42, hot: true },
    { percent: 56, hot: true },
    { percent: 64, hot: true },
    { percent: 72, hot: true },
    { percent: 70, hot: true },
    { percent: 76, hot: true },
    { percent: 82, hot: true },
    { percent: 80, hot: true },
    { percent: 86, hot: true },
    { percent: 90, hot: true },
    { percent: 88, hot: true },
    { percent: 92, hot: true },
    { percent: 96, hot: true },
    { percent: 94, hot: true },
    { percent: 98, hot: true },
  ],
  lines: [
    {
      time: '09:41:03.219',
      level: 'WARN',
      message: 'parseLegacyCursor() is deprecated callsite=db/cursor.ts:44',
    },
    {
      time: '09:41:03.884',
      level: 'WARN',
      message: 'parseLegacyCursor() is deprecated callsite=api/events.ts:210',
    },
    {
      time: '09:41:04.402',
      level: 'WARN',
      message: 'parseLegacyCursor() is deprecated callsite=jobs/export.ts:88',
    },
    {
      time: '09:41:05.118',
      level: 'WARN',
      message: 'parseLegacyCursor() is deprecated callsite=db/cursor.ts:44',
    },
  ],
  fix: {
    title: 'Migration PR',
    subtitle: 'One PR, 41 callsites',
    note: 'Mechanical rewrite to parseCursor() with the same semantics. I will split it per directory so reviewers can take a slice each.',
    file: 'codemod · parseLegacyCursor → parseCursor',
    cta: 'Open 4 stacked PRs',
    hunk: [
      { no: '44', sign: '-', text: 'const c = parseLegacyCursor(req.query.cursor);' },
      { no: '44', sign: '+', text: 'const c = parseCursor(req.query.cursor);' },
    ],
    steps: [
      'stack the PRs by directory (db, api, jobs, web)',
      'drop the deprecated export in v4.20',
    ],
  },
}

export const LOG_ITEMS = [LOG_INGEST_LATENCY, LOG_DEPRECATIONS]
