import type { ConsoleItem } from '../../console-model'

export const REVIEW_FANOUT: ConsoleItem = {
  id: 'sample:#4471',
  handle: '#4471',
  triage: null,
  kind: 'review',
  label: 'Review · #4471',
  severity: 'info',
  age: '52m',
  title: 'Rate-limit the webhook fan-out',
  subtitle: 'feat/webhook-ratelimit → main · netko/api-gateway',
  meta: '1 blocker · 6 files',
  badge: 'REVIEW',
  badge2: '1 BLOCKER',
  confidence: 'blocking',
  read: 'The retry budget is unbounded on 5xx — a single bad endpoint can re-enqueue itself forever. Everything else in this PR reads well.',
  fixLabel: 'Apply suggestion',
  evidenceLabel: 'Show the hot loop',
  diff: '+284 −61',
  fileCount: '6',
  checks: '12 passing',
  author: 'Jamie Doss',
  blockerFile: 'src/webhooks/fanout.ts',
  blockerKind: 'UNBOUNDED RETRY',
  blockerNote:
    'Line 84 retries on any non-2xx with no ceiling. Cap it at 5 attempts with exponential backoff, or the queue drains into itself under a partial outage.',
  hunk: [
    { no: '82', sign: '', text: 'for (const target of targets) {' },
    { no: '83', sign: '', text: '  const res = await post(target, payload);' },
    { no: '84', sign: '+', text: '  while (!res.ok) await post(target, payload);' },
    { no: '85', sign: '', text: '  metrics.inc("fanout.delivered");' },
    { no: '86', sign: '', text: '}' },
  ],
  files: [
    { path: 'src/webhooks/fanout.ts', diff: '+96 −12', note: '1 blocker', tone: 'bad' },
    { path: 'src/webhooks/queue.ts', diff: '+74 −8', note: 'ok', tone: 'muted' },
    { path: 'src/webhooks/verify.ts', diff: '+41 −29', note: '1 note', tone: 'warn' },
    { path: 'src/config/limits.ts', diff: '+38 −0', note: 'ok', tone: 'muted' },
    { path: 'test/fanout.test.ts', diff: '+31 −4', note: 'ok', tone: 'muted' },
    { path: 'docs/webhooks.md', diff: '+4 −8', note: 'ok', tone: 'muted' },
  ],
  fix: {
    title: 'Whiskers’ suggestion',
    subtitle: 'Replaces the unbounded loop on line 84',
    note: 'A capped retry with backoff, plus the ceiling pulled into config so ops can change it without a deploy.',
    file: 'src/webhooks/fanout.ts',
    cta: 'Commit to this branch',
    hunk: [
      { no: '83', sign: '-', text: '  const res = await post(target, payload);' },
      { no: '83', sign: '+', text: '  let res = await post(target, payload);' },
      { no: '84', sign: '-', text: '  while (!res.ok) await post(target, payload);' },
      { no: '84', sign: '+', text: '  let attempt = 0;' },
      { no: '85', sign: '+', text: '  while (!res.ok && attempt < LIMITS.fanoutRetries) {' },
      { no: '86', sign: '+', text: '    await sleep(backoff(attempt++));' },
      { no: '87', sign: '+', text: '    res = await post(target, payload);' },
      { no: '88', sign: '+', text: '  }' },
    ],
    steps: [
      'add LIMITS.fanoutRetries = 5 to src/config/limits.ts',
      'extend test/fanout.test.ts with a partial-outage case',
      'clear the blocker and re-run checks',
    ],
  },
}

export const REVIEW_SHIPPER: ConsoleItem = {
  id: 'sample:#4468',
  handle: '#4468',
  triage: null,
  kind: 'review',
  label: 'Review · #4468',
  severity: 'ok',
  age: '6h',
  title: 'Drop legacy log shipper',
  subtitle: 'chore/drop-log-shipper → main · netko/api-gateway',
  meta: 'Whiskers approved',
  badge: 'REVIEW',
  badge2: 'NO FINDINGS',
  confidence: 'no findings',
  read: 'Pure deletion. Every removed export has no remaining references, and the two config keys are already unused in production.',
  fixLabel: 'Approve on my behalf',
  evidenceLabel: 'Show reference scan',
  diff: '+12 −1,904',
  fileCount: '31',
  checks: '12 passing',
  author: 'Priya Lal',
  blockerFile: 'src/log/shipper.ts',
  blockerKind: 'DELETED',
  blockerNote:
    'Nothing to flag. The last caller went away in #4402, and I re-ran the reference scan on this branch.',
  hunk: [
    { no: '1', sign: '-', text: 'export class LegacyShipper {' },
    { no: '2', sign: '-', text: '  constructor(private endpoint: string) {}' },
    { no: '3', sign: '-', text: '}' },
  ],
  files: [
    { path: 'src/log/shipper.ts', diff: '+0 −412', note: 'deleted', tone: 'muted' },
    { path: 'src/log/index.ts', diff: '+4 −38', note: 'ok', tone: 'muted' },
    { path: 'config/logging.yaml', diff: '+2 −16', note: 'ok', tone: 'muted' },
    { path: 'test/shipper.test.ts', diff: '+0 −288', note: 'deleted', tone: 'muted' },
  ],
  fix: {
    title: 'Approve #4468',
    subtitle: 'No findings across 31 files',
    note: 'I ran the reference scan twice: no imports of LegacyShipper remain on this branch or on main.',
    file: 'reference scan · 31 files',
    cta: 'Approve and merge',
    hunk: [
      { no: '1', sign: '', text: 'grep -r "LegacyShipper" src/ test/' },
      { no: '2', sign: '', text: '→ 0 matches' },
    ],
    steps: ['merge on green checks', 'remove the shipper dashboard panel'],
  },
}

export const REVIEW_ITEMS = [REVIEW_FANOUT, REVIEW_SHIPPER]
