import type { SampleEventSeed, SampleFacets, SampleIssueSeed } from '../types'

export const SAMPLE_ISSUE_PREFIX = 'sample-'
export const SAMPLE_PROJECT_ID = 'sample'

const MINUTE = 60_000
const HOUR = 60 * MINUTE
const DAY = 24 * HOUR

export const SAMPLE_ISSUE_SEEDS: SampleIssueSeed[] = [
  {
    id: 'sample-2041',
    title: 'TypeError: cannot read `sessionId` of undefined',
    level: 'error',
    status: 'unresolved',
    eventCount: 14_208,
    userCount: 3_104,
    firstSeenAgoMs: 9 * DAY,
    lastSeenAgoMs: 18 * MINUTE,
    firstRelease: 'v4.17.0',
    lastRelease: 'v4.18.2',
    resolvedInRelease: null,
    archivedForMs: null,
    archiveUntilEvents: null,
    archiveUntilUsers: null,
    badges: ['regressed', 'spiking'],
    trend: [12, 8, 10, 9, 14, 0, 0, 0, 0, 3, 40, 380, 2210, 11_522],
    culprit: 'src/auth/session.ts in resolveSession',
  },
  {
    id: 'sample-2039',
    title: 'TimeoutError: upstream billing service',
    level: 'error',
    status: 'unresolved',
    eventCount: 2_840,
    userCount: 611,
    firstSeenAgoMs: 3 * DAY,
    lastSeenAgoMs: 4 * HOUR,
    firstRelease: 'v4.18.1',
    lastRelease: 'v4.18.1',
    resolvedInRelease: null,
    archivedForMs: null,
    archiveUntilEvents: null,
    archiveUntilUsers: null,
    badges: ['new'],
    trend: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 410, 1_620, 810],
    culprit: 'src/billing/client.ts in charge',
  },
  {
    id: 'sample-2044',
    title: 'ValidationError: payload missing trace_id',
    level: 'warning',
    status: 'unresolved',
    eventCount: 612,
    userCount: 42,
    firstSeenAgoMs: 30 * DAY,
    lastSeenAgoMs: 11 * HOUR,
    firstRelease: 'v4.15.0',
    lastRelease: 'v4.18.0',
    resolvedInRelease: null,
    archivedForMs: null,
    archiveUntilEvents: null,
    archiveUntilUsers: null,
    badges: [],
    trend: [44, 51, 38, 47, 40, 52, 39, 41, 48, 45, 37, 43, 46, 41],
    culprit: 'src/ingest/validate.ts in assertTraceId',
  },
  {
    id: 'sample-2030',
    title: 'FetchError: sdk-js failed to flush on unload',
    level: 'warning',
    status: 'archived',
    eventCount: 318,
    userCount: 204,
    firstSeenAgoMs: 40 * DAY,
    lastSeenAgoMs: 2 * DAY,
    firstRelease: 'v4.12.0',
    lastRelease: 'v4.18.0',
    resolvedInRelease: null,
    archivedForMs: null,
    archiveUntilEvents: 418,
    archiveUntilUsers: null,
    badges: [],
    trend: [30, 22, 25, 19, 24, 28, 21, 26, 23, 20, 27, 22, 0, 0],
    culprit: 'packages/sdk-js/src/transport.ts in flush',
  },
  {
    id: 'sample-2036',
    title: 'RangeError in cursor paging',
    level: 'error',
    status: 'resolved',
    eventCount: 1_204,
    userCount: 96,
    firstSeenAgoMs: 12 * DAY,
    lastSeenAgoMs: DAY,
    firstRelease: 'v4.16.3',
    lastRelease: 'v4.18.1',
    resolvedInRelease: 'v4.18.1',
    archivedForMs: null,
    archiveUntilEvents: null,
    archiveUntilUsers: null,
    badges: [],
    trend: [80, 92, 101, 88, 95, 110, 97, 104, 120, 115, 99, 103, 0, 0],
    culprit: 'src/db/cursor.ts in pageAfter',
  },
]

export const SAMPLE_EVENT_SEEDS: Record<string, SampleEventSeed> = {
  'sample-2041': {
    message: "TypeError: cannot read 'sessionId' of undefined",
    environment: 'production',
    release: 'v4.18.2',
    frames: [
      {
        file: 'src/auth/session.ts',
        function: 'resolveSession',
        line: 118,
        column: 24,
        isInApp: true,
        context: '  const id = ctx.session.sessionId;',
      },
      {
        file: 'src/webhooks/verify.ts',
        function: 'verifyWebhook',
        line: 204,
        column: 9,
        isInApp: true,
        context: '  const id = resolveSession(ctx).sessionId;',
      },
      {
        file: 'node_modules/elysia/dist/handler.js',
        function: 'handle',
        line: 412,
        column: 18,
        isInApp: false,
        context: null,
      },
      {
        file: 'node_modules/elysia/dist/compose.js',
        function: 'compose',
        line: 88,
        column: 13,
        isInApp: false,
        context: null,
      },
      {
        file: 'src/webhooks/route.ts',
        function: 'handler',
        line: 61,
        column: 5,
        isInApp: true,
        context: '  return verifyWebhook(ctx)',
      },
    ],
    breadcrumbs: [
      { type: 'default', category: 'deploy', level: 'info', message: 'v4.18.2 rolled out' },
      {
        type: 'http',
        category: 'http',
        level: 'info',
        message: 'POST /webhooks/stripe 200 (48ms)',
      },
      {
        type: 'navigation',
        category: 'navigation',
        level: 'info',
        message: '/billing → /webhooks',
      },
      {
        type: 'query',
        category: 'db.query',
        level: 'info',
        message: 'select * from session where id = $1',
      },
      {
        type: 'error',
        category: 'auth',
        level: 'error',
        message: 'resolveSession(ctx) called without session',
      },
    ],
    tags: { runtime: 'node 22.4.0', region: 'eu-west-1', handled: 'no' },
    request: { method: 'POST', url: '/webhooks/stripe' },
    logs: [
      {
        level: 'ERROR',
        service: 'api',
        message: "cannot read 'sessionId' of undefined req=7f21ac",
      },
      {
        level: 'ERROR',
        service: 'api',
        message: 'verifyWebhook failed after 1 attempt status=500',
      },
      { level: 'WARN', service: 'api', message: 'p95 latency 812ms exceeds 500ms' },
    ],
  },
  'sample-2039': {
    message: 'TimeoutError: upstream billing service after 5000ms',
    environment: 'production',
    release: 'v4.18.1',
    frames: [
      {
        file: 'src/billing/client.ts',
        function: 'charge',
        line: 64,
        column: 11,
        isInApp: true,
        context: '  const res = await fetch(url, { timeout: 5000 });',
      },
      {
        file: 'src/billing/renew.ts',
        function: 'renewSubscription',
        line: 119,
        column: 5,
        isInApp: true,
        context: '  await charge(subscription)',
      },
    ],
    breadcrumbs: [
      {
        type: 'default',
        category: 'vendor',
        level: 'warning',
        message: 'billing vendor reports degraded writes',
      },
      { type: 'http', category: 'http', level: 'error', message: 'POST /charges timed out' },
    ],
    tags: { vendor: 'billing-api', region: 'eu-west-1', handled: 'yes' },
    request: null,
    logs: [
      { level: 'ERROR', service: 'billing', message: 'TimeoutError after=5000ms' },
      { level: 'INFO', service: 'billing', message: 'charge succeeded on retry amount=4900' },
    ],
  },
}

export const SAMPLE_FACETS: SampleFacets = {
  environments: ['production', 'staging'],
  releases: ['v4.18.2', 'v4.18.1', 'v4.18.0'],
  tagKeys: {
    browser: ['Chrome', 'Safari', 'Firefox'],
    region: ['eu-west-1', 'us-east-1'],
    runtime: ['node 22.4.0', 'node 20.11.1'],
  },
}
