export const REQUIRED_PRODUCTION_ENV = [
  'BASE_URL',
  'DATABASE_URL',
  'AUTH_SECRET',
  'ENCRYPTION_KEY',
  'WHISKERS_URL',
  'INTERNAL_TOKEN',
] as const
export const MIN_AUTH_SECRET_LENGTH = 32
export const MIN_AUTH_SECRET_DISTINCT_CHARS = 12
