import type { SectionDefinition } from '../../../shared/console-model'

export const PULL_REQUESTS_SECTION: SectionDefinition = {
  title: 'Pull requests',
  subtitle: '6 open across 14 repositories · Whiskers reviews every push',
  actions: [
    { label: 'Filters', variant: 'outline' },
    { label: 'Review next', variant: 'solid' },
  ],
  stats: [
    { label: 'Open', value: '6', note: '2 awaiting you' },
    { label: 'Whiskers blockers', value: '3', note: 'across 2 repos' },
    { label: 'Median review', value: '41m', note: 'first response' },
    { label: 'Merged this week', value: '23', note: '9 auto-approved' },
  ],
  tabs: ['Open', 'Draft', 'Merged', 'Closed'],
  table: {
    grid: '1fr 180px 150px 110px 130px 90px',
    columns: [
      { label: 'Pull request' },
      { label: 'Repository' },
      { label: 'Whiskers' },
      { label: 'Diff' },
      { label: 'Author' },
      { label: 'Updated', align: 'end' },
    ],
    rows: [
      [
        {
          kind: 'text',
          text: '#4471 Rate-limit the webhook fan-out',
          strong: true,
          dot: 'critical',
        },
        { kind: 'text', text: 'api-gateway', mono: true },
        { kind: 'pill', text: '1 blocker', tone: 'bad' },
        { kind: 'text', text: '+284 −61', mono: true },
        { kind: 'text', text: 'Jamie Doss', tone: 'muted' },
        { kind: 'text', text: '52m', tone: 'muted', align: 'end' },
      ],
      [
        {
          kind: 'text',
          text: '#4470 Cache service tokens per region',
          strong: true,
          dot: 'warning',
        },
        { kind: 'text', text: 'api-gateway', mono: true },
        { kind: 'pill', text: '2 suggestions', tone: 'warn' },
        { kind: 'text', text: '+142 −18', mono: true },
        { kind: 'text', text: 'Ada Kwan', tone: 'muted' },
        { kind: 'text', text: '2h', tone: 'muted', align: 'end' },
      ],
      [
        {
          kind: 'text',
          text: '#4469 Emit OTel spans from the ingest path',
          strong: true,
          dot: 'info',
        },
        { kind: 'text', text: 'collector', mono: true },
        { kind: 'pill', text: 'Reviewing…', tone: 'neutral' },
        { kind: 'text', text: '+512 −44', mono: true },
        { kind: 'text', text: 'Sam Ito', tone: 'muted' },
        { kind: 'text', text: '3h', tone: 'muted', align: 'end' },
      ],
      [
        { kind: 'text', text: '#4468 Drop legacy log shipper', strong: true, dot: 'ok' },
        { kind: 'text', text: 'api-gateway', mono: true },
        { kind: 'pill', text: 'No findings', tone: 'ok' },
        { kind: 'text', text: '+12 −1,904', mono: true },
        { kind: 'text', text: 'Priya Lal', tone: 'muted' },
        { kind: 'text', text: '6h', tone: 'muted', align: 'end' },
      ],
      [
        {
          kind: 'text',
          text: '#4465 Add cursor pagination to /events',
          strong: true,
          dot: 'warning',
        },
        { kind: 'text', text: 'api-gateway', mono: true },
        { kind: 'pill', text: '2 suggestions', tone: 'warn' },
        { kind: 'text', text: '+96 −14', mono: true },
        { kind: 'text', text: 'Jamie Doss', tone: 'muted' },
        { kind: 'text', text: '9h', tone: 'muted', align: 'end' },
      ],
      [
        { kind: 'text', text: '#4461 Split the retention worker', strong: true, dot: 'ok' },
        { kind: 'text', text: 'workers', mono: true },
        { kind: 'pill', text: 'No findings', tone: 'ok' },
        { kind: 'text', text: '+208 −96', mono: true },
        { kind: 'text', text: 'Mara Reyes', tone: 'muted' },
        { kind: 'text', text: '1d', tone: 'muted', align: 'end' },
      ],
    ],
    footer: 'Whiskers posts one review per push · never merges on your behalf',
  },
}

export const REPOSITORIES_SECTION: SectionDefinition = {
  title: 'Repositories',
  subtitle: 'Netko Labs · 14 connected, 11 actively watched',
  actions: [
    { label: 'Pause watching', variant: 'outline' },
    { label: 'Connect repository', variant: 'solid' },
  ],
  stats: [
    { label: 'Connected', value: '14', note: 'via GitHub app' },
    { label: 'Watched', value: '11', note: '3 paused' },
    { label: 'Reviews (7d)', value: '96', note: '41 with findings' },
    { label: 'Events (24h)', value: '1.2M', note: 'all repos' },
  ],
  tabs: ['All', 'Watched', 'Paused'],
  table: {
    grid: '1fr 120px 110px 110px 150px 100px',
    columns: [
      { label: 'Repository' },
      { label: 'Language' },
      { label: 'Reviews 7d' },
      { label: 'Errors 24h' },
      { label: 'Review coverage' },
      { label: 'Last push', align: 'end' },
    ],
    rows: [
      [
        { kind: 'text', text: 'netko/api-gateway', mono: true, strong: true, dot: 'ok' },
        { kind: 'text', text: 'TypeScript', tone: 'muted' },
        { kind: 'text', text: '41', mono: true },
        { kind: 'text', text: '28', mono: true, tone: 'bad' },
        { kind: 'bar', percent: 94, tone: 'ok', note: '94%' },
        { kind: 'text', text: '4m', tone: 'muted', align: 'end' },
      ],
      [
        { kind: 'text', text: 'netko/collector', mono: true, strong: true, dot: 'ok' },
        { kind: 'text', text: 'Go', tone: 'muted' },
        { kind: 'text', text: '22', mono: true },
        { kind: 'text', text: '9', mono: true },
        { kind: 'bar', percent: 88, tone: 'ok', note: '88%' },
        { kind: 'text', text: '26m', tone: 'muted', align: 'end' },
      ],
      [
        { kind: 'text', text: 'netko/workers', mono: true, strong: true, dot: 'ok' },
        { kind: 'text', text: 'TypeScript', tone: 'muted' },
        { kind: 'text', text: '14', mono: true },
        { kind: 'text', text: '4', mono: true },
        { kind: 'bar', percent: 71, tone: 'warn', note: '71%' },
        { kind: 'text', text: '2h', tone: 'muted', align: 'end' },
      ],
      [
        { kind: 'text', text: 'netko/web', mono: true, strong: true, dot: 'ok' },
        { kind: 'text', text: 'TypeScript', tone: 'muted' },
        { kind: 'text', text: '11', mono: true },
        { kind: 'text', text: '6', mono: true },
        { kind: 'bar', percent: 62, tone: 'warn', note: '62%' },
        { kind: 'text', text: '5h', tone: 'muted', align: 'end' },
      ],
      [
        { kind: 'text', text: 'netko/terraform', mono: true, strong: true, dot: 'idle' },
        { kind: 'text', text: 'HCL', tone: 'muted' },
        { kind: 'text', text: '6', mono: true },
        { kind: 'text', text: '0', tone: 'muted' },
        { kind: 'bar', percent: 34, tone: 'neutral', note: '34%' },
        { kind: 'text', text: '1d', tone: 'muted', align: 'end' },
      ],
      [
        { kind: 'text', text: 'netko/sdk-js', mono: true, strong: true, dot: 'idle' },
        { kind: 'text', text: 'TypeScript', tone: 'muted' },
        { kind: 'text', text: '2', mono: true },
        { kind: 'text', text: '1', tone: 'muted' },
        { kind: 'bar', percent: 80, tone: 'ok', note: '80%' },
        { kind: 'text', text: '3d', tone: 'muted', align: 'end' },
      ],
    ],
    footer: 'Paused repositories keep ingesting errors but are not reviewed',
  },
}

export const REVIEW_RULES_SECTION: SectionDefinition = {
  title: 'Review rules',
  subtitle: 'Plain-English instructions Whiskers follows on every pull request',
  actions: [
    { label: 'Rule history', variant: 'outline' },
    { label: 'Write a rule', variant: 'solid' },
  ],
  stats: [
    { label: 'Active rules', value: '9', note: '2 org-wide' },
    { label: 'Triggered 30d', value: '214', note: '41 became blockers' },
    { label: 'Muted', value: '2', note: 'by Priya' },
    { label: 'False positives', value: '3%', note: 'you dismissed 7' },
  ],
  tabs: ['Active', 'Muted', 'Drafts'],
  table: {
    grid: '1fr 170px 120px 130px 110px',
    columns: [
      { label: 'Rule' },
      { label: 'Scope' },
      { label: 'Triggered 30d' },
      { label: 'Author' },
      { label: 'State', align: 'end' },
    ],
    rows: [
      [
        {
          kind: 'text',
          text: 'Never let a retry loop run without a ceiling — flag it as a blocker.',
          wrap: true,
          strong: true,
        },
        { kind: 'text', text: 'All repositories', tone: 'muted' },
        { kind: 'text', text: '18', mono: true },
        { kind: 'text', text: 'Mara Reyes', tone: 'muted' },
        { kind: 'pill', text: 'blocker', tone: 'bad', align: 'end' },
      ],
      [
        {
          kind: 'text',
          text: 'Any new endpoint must emit an OTel span with the route as its name.',
          wrap: true,
        },
        { kind: 'text', text: 'api-gateway, collector', tone: 'muted' },
        { kind: 'text', text: '42', mono: true },
        { kind: 'text', text: 'Priya Lal', tone: 'muted' },
        { kind: 'pill', text: 'blocker', tone: 'bad', align: 'end' },
      ],
      [
        { kind: 'text', text: 'Ask for a test when a file in src/billing/** changes.', wrap: true },
        { kind: 'text', text: 'src/billing/**', tone: 'muted' },
        { kind: 'text', text: '26', mono: true },
        { kind: 'text', text: 'Ada Kwan', tone: 'muted' },
        { kind: 'pill', text: 'suggestion', tone: 'warn', align: 'end' },
      ],
      [
        {
          kind: 'text',
          text: 'Prefer ctx.session over reading auth headers directly.',
          wrap: true,
        },
        { kind: 'text', text: 'src/auth/**', tone: 'muted' },
        { kind: 'text', text: '31', mono: true },
        { kind: 'text', text: 'Mara Reyes', tone: 'muted' },
        { kind: 'pill', text: 'suggestion', tone: 'warn', align: 'end' },
      ],
      [
        { kind: 'text', text: 'Do not comment on generated files or lockfiles.', wrap: true },
        { kind: 'text', text: 'All repositories', tone: 'muted' },
        { kind: 'text', text: '—', tone: 'muted' },
        { kind: 'text', text: 'Org default', tone: 'muted' },
        { kind: 'pill', text: 'filter', tone: 'neutral', align: 'end' },
      ],
      [
        { kind: 'text', text: 'Keep review comments under four sentences.', wrap: true },
        { kind: 'text', text: 'All repositories', tone: 'muted' },
        { kind: 'text', text: '—', tone: 'muted' },
        { kind: 'text', text: 'Org default', tone: 'muted' },
        { kind: 'pill', text: 'tone', tone: 'neutral', align: 'end' },
      ],
    ],
    footer: 'Rules are prose, not config — Whiskers quotes the rule it applied in every comment',
  },
}
