/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMonitorRouteImport } from './routes/api/monitor'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleSectionRouteImport } from './routes/console/$section'
import { Route as ConsoleCodebaseMapRouteImport } from './routes/console/codebase-map'
import { Route as ConsoleLiveLogsRouteImport } from './routes/console/live-logs'
import { Route as ConsoleOverviewRouteImport } from './routes/console/overview'
import { Route as ConsolePullRequestsRouteImport } from './routes/console/pull-requests'
import { Route as ConsoleRepositoriesRouteImport } from './routes/console/repositories'
import { Route as ConsoleReviewRulesRouteImport } from './routes/console/review-rules'
import { Route as ConsoleSavedQueriesRouteImport } from './routes/console/saved-queries'
import { Route as ConsoleServicesRouteImport } from './routes/console/services'
import { Route as ConsoleSettingsRouteImport } from './routes/console/settings'
import { Route as OtlpSplatRouteImport } from './routes/otlp/$'
import { Route as V1SplatRouteImport } from './routes/v1/$'
import { Route as WebhooksSplatRouteImport } from './routes/webhooks/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ConsoleAlertsIndexRouteImport } from './routes/console/alerts.index'
import { Route as ConsoleAlertsRuleIdRouteImport } from './routes/console/alerts.$ruleId'
import { Route as ConsoleAlertsActivityRouteImport } from './routes/console/alerts.activity'
import { Route as ConsoleAlertsDestinationsRouteImport } from './routes/console/alerts.destinations'
import { Route as ConsoleAlertsNewRouteImport } from './routes/console/alerts.new'
import { Route as ConsoleIssuesIssueIdRouteImport } from './routes/console/issues.$issueId'
import { Route as ConsoleProjectsIndexRouteImport } from './routes/console/projects.index'
import { Route as ConsoleProjectsProjectIdRouteImport } from './routes/console/projects.$projectId'
import { Route as ConsoleProjectsNewRouteImport } from './routes/console/projects.new'
import { Route as ConsoleReleasesVersionRouteImport } from './routes/console/releases.$version'
import { Route as ConsoleReviewsReviewIdRouteImport } from './routes/console/reviews.$reviewId'
import { Route as ConsoleSettingsIndexRouteImport } from './routes/console/settings.index'
import { Route as ConsoleSettingsAccountRouteImport } from './routes/console/settings.account'
import { Route as ConsoleSettingsApiKeysRouteImport } from './routes/console/settings.api-keys'
import { Route as ConsoleSettingsGeneralRouteImport } from './routes/console/settings.general'
import { Route as ConsoleSettingsGithubRouteImport } from './routes/console/settings.github'
import { Route as ConsoleSettingsMembersRouteImport } from './routes/console/settings.members'
import { Route as ConsoleTracesIndexRouteImport } from './routes/console/traces.index'
import { Route as ConsoleTracesTraceIdRouteImport } from './routes/console/traces.$traceId'
import { Route as ConsoleTriageBucketRouteImport } from './routes/console/triage.$bucket'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorRoute = ApiMonitorRouteImport.update({
  id: '/api/monitor',
  path: '/api/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSectionRoute = ConsoleSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCodebaseMapRoute = ConsoleCodebaseMapRouteImport.update({
  id: '/codebase-map',
  path: '/codebase-map',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleLiveLogsRoute = ConsoleLiveLogsRouteImport.update({
  id: '/live-logs',
  path: '/live-logs',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOverviewRoute = ConsoleOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePullRequestsRoute = ConsolePullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRepositoriesRoute = ConsoleRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReviewRulesRoute = ConsoleReviewRulesRouteImport.update({
  id: '/review-rules',
  path: '/review-rules',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSavedQueriesRoute = ConsoleSavedQueriesRouteImport.update({
  id: '/saved-queries',
  path: '/saved-queries',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleServicesRoute = ConsoleServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const OtlpSplatRoute = OtlpSplatRouteImport.update({
  id: '/otlp/$',
  path: '/otlp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksSplatRoute = WebhooksSplatRouteImport.update({
  id: '/webhooks/$',
  path: '/webhooks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAlertsIndexRoute = ConsoleAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAlertsRuleIdRoute = ConsoleAlertsRuleIdRouteImport.update({
  id: '/alerts/$ruleId',
  path: '/alerts/$ruleId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAlertsActivityRoute = ConsoleAlertsActivityRouteImport.update({
  id: '/alerts/activity',
  path: '/alerts/activity',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAlertsDestinationsRoute =
  ConsoleAlertsDestinationsRouteImport.update({
    id: '/alerts/destinations',
    path: '/alerts/destinations',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleAlertsNewRoute = ConsoleAlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleIssuesIssueIdRoute = ConsoleIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectsIndexRoute = ConsoleProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectsProjectIdRoute =
  ConsoleProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleProjectsNewRoute = ConsoleProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReleasesVersionRoute = ConsoleReleasesVersionRouteImport.update({
  id: '/releases/$version',
  path: '/releases/$version',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReviewsReviewIdRoute = ConsoleReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsIndexRoute = ConsoleSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleSettingsRoute,
} as any)
const ConsoleSettingsAccountRoute = ConsoleSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ConsoleSettingsRoute,
} as any)
const ConsoleSettingsApiKeysRoute = ConsoleSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ConsoleSettingsRoute,
} as any)
const ConsoleSettingsGeneralRoute = ConsoleSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => ConsoleSettingsRoute,
} as any)
const ConsoleSettingsGithubRoute = ConsoleSettingsGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => ConsoleSettingsRoute,
} as any)
const ConsoleSettingsMembersRoute = ConsoleSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ConsoleSettingsRoute,
} as any)
const ConsoleTracesIndexRoute = ConsoleTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTracesTraceIdRoute = ConsoleTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTriageBucketRoute = ConsoleTriageBucketRouteImport.update({
  id: '/triage/$bucket',
  path: '/triage/$bucket',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitor': typeof ApiMonitorRoute
  '/console/$section': typeof ConsoleSectionRoute
  '/console/codebase-map': typeof ConsoleCodebaseMapRoute
  '/console/live-logs': typeof ConsoleLiveLogsRoute
  '/console/overview': typeof ConsoleOverviewRoute
  '/console/pull-requests': typeof ConsolePullRequestsRoute
  '/console/repositories': typeof ConsoleRepositoriesRoute
  '/console/review-rules': typeof ConsoleReviewRulesRoute
  '/console/saved-queries': typeof ConsoleSavedQueriesRoute
  '/console/services': typeof ConsoleServicesRoute
  '/console/settings': typeof ConsoleSettingsRouteWithChildren
  '/otlp/$': typeof OtlpSplatRoute
  '/v1/$': typeof V1SplatRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/alerts/$ruleId': typeof ConsoleAlertsRuleIdRoute
  '/console/alerts/activity': typeof ConsoleAlertsActivityRoute
  '/console/alerts/destinations': typeof ConsoleAlertsDestinationsRoute
  '/console/alerts/new': typeof ConsoleAlertsNewRoute
  '/console/issues/$issueId': typeof ConsoleIssuesIssueIdRoute
  '/console/projects/$projectId': typeof ConsoleProjectsProjectIdRoute
  '/console/projects/new': typeof ConsoleProjectsNewRoute
  '/console/releases/$version': typeof ConsoleReleasesVersionRoute
  '/console/reviews/$reviewId': typeof ConsoleReviewsReviewIdRoute
  '/console/settings/account': typeof ConsoleSettingsAccountRoute
  '/console/settings/api-keys': typeof ConsoleSettingsApiKeysRoute
  '/console/settings/general': typeof ConsoleSettingsGeneralRoute
  '/console/settings/github': typeof ConsoleSettingsGithubRoute
  '/console/settings/members': typeof ConsoleSettingsMembersRoute
  '/console/traces/$traceId': typeof ConsoleTracesTraceIdRoute
  '/console/triage/$bucket': typeof ConsoleTriageBucketRoute
  '/console/alerts/': typeof ConsoleAlertsIndexRoute
  '/console/projects/': typeof ConsoleProjectsIndexRoute
  '/console/settings/': typeof ConsoleSettingsIndexRoute
  '/console/traces/': typeof ConsoleTracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitor': typeof ApiMonitorRoute
  '/console/$section': typeof ConsoleSectionRoute
  '/console/codebase-map': typeof ConsoleCodebaseMapRoute
  '/console/live-logs': typeof ConsoleLiveLogsRoute
  '/console/overview': typeof ConsoleOverviewRoute
  '/console/pull-requests': typeof ConsolePullRequestsRoute
  '/console/repositories': typeof ConsoleRepositoriesRoute
  '/console/review-rules': typeof ConsoleReviewRulesRoute
  '/console/saved-queries': typeof ConsoleSavedQueriesRoute
  '/console/services': typeof ConsoleServicesRoute
  '/otlp/$': typeof OtlpSplatRoute
  '/v1/$': typeof V1SplatRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/console': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/alerts/$ruleId': typeof ConsoleAlertsRuleIdRoute
  '/console/alerts/activity': typeof ConsoleAlertsActivityRoute
  '/console/alerts/destinations': typeof ConsoleAlertsDestinationsRoute
  '/console/alerts/new': typeof ConsoleAlertsNewRoute
  '/console/issues/$issueId': typeof ConsoleIssuesIssueIdRoute
  '/console/projects/$projectId': typeof ConsoleProjectsProjectIdRoute
  '/console/projects/new': typeof ConsoleProjectsNewRoute
  '/console/releases/$version': typeof ConsoleReleasesVersionRoute
  '/console/reviews/$reviewId': typeof ConsoleReviewsReviewIdRoute
  '/console/settings/account': typeof ConsoleSettingsAccountRoute
  '/console/settings/api-keys': typeof ConsoleSettingsApiKeysRoute
  '/console/settings/general': typeof ConsoleSettingsGeneralRoute
  '/console/settings/github': typeof ConsoleSettingsGithubRoute
  '/console/settings/members': typeof ConsoleSettingsMembersRoute
  '/console/traces/$traceId': typeof ConsoleTracesTraceIdRoute
  '/console/triage/$bucket': typeof ConsoleTriageBucketRoute
  '/console/alerts': typeof ConsoleAlertsIndexRoute
  '/console/projects': typeof ConsoleProjectsIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/traces': typeof ConsoleTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitor': typeof ApiMonitorRoute
  '/console/$section': typeof ConsoleSectionRoute
  '/console/codebase-map': typeof ConsoleCodebaseMapRoute
  '/console/live-logs': typeof ConsoleLiveLogsRoute
  '/console/overview': typeof ConsoleOverviewRoute
  '/console/pull-requests': typeof ConsolePullRequestsRoute
  '/console/repositories': typeof ConsoleRepositoriesRoute
  '/console/review-rules': typeof ConsoleReviewRulesRoute
  '/console/saved-queries': typeof ConsoleSavedQueriesRoute
  '/console/services': typeof ConsoleServicesRoute
  '/console/settings': typeof ConsoleSettingsRouteWithChildren
  '/otlp/$': typeof OtlpSplatRoute
  '/v1/$': typeof V1SplatRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/alerts/$ruleId': typeof ConsoleAlertsRuleIdRoute
  '/console/alerts/activity': typeof ConsoleAlertsActivityRoute
  '/console/alerts/destinations': typeof ConsoleAlertsDestinationsRoute
  '/console/alerts/new': typeof ConsoleAlertsNewRoute
  '/console/issues/$issueId': typeof ConsoleIssuesIssueIdRoute
  '/console/projects/$projectId': typeof ConsoleProjectsProjectIdRoute
  '/console/projects/new': typeof ConsoleProjectsNewRoute
  '/console/releases/$version': typeof ConsoleReleasesVersionRoute
  '/console/reviews/$reviewId': typeof ConsoleReviewsReviewIdRoute
  '/console/settings/account': typeof ConsoleSettingsAccountRoute
  '/console/settings/api-keys': typeof ConsoleSettingsApiKeysRoute
  '/console/settings/general': typeof ConsoleSettingsGeneralRoute
  '/console/settings/github': typeof ConsoleSettingsGithubRoute
  '/console/settings/members': typeof ConsoleSettingsMembersRoute
  '/console/traces/$traceId': typeof ConsoleTracesTraceIdRoute
  '/console/triage/$bucket': typeof ConsoleTriageBucketRoute
  '/console/alerts/': typeof ConsoleAlertsIndexRoute
  '/console/projects/': typeof ConsoleProjectsIndexRoute
  '/console/settings/': typeof ConsoleSettingsIndexRoute
  '/console/traces/': typeof ConsoleTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/sign-in'
    | '/api/$'
    | '/api/health'
    | '/api/monitor'
    | '/console/$section'
    | '/console/codebase-map'
    | '/console/live-logs'
    | '/console/overview'
    | '/console/pull-requests'
    | '/console/repositories'
    | '/console/review-rules'
    | '/console/saved-queries'
    | '/console/services'
    | '/console/settings'
    | '/otlp/$'
    | '/v1/$'
    | '/webhooks/$'
    | '/console/'
    | '/api/auth/$'
    | '/console/alerts/$ruleId'
    | '/console/alerts/activity'
    | '/console/alerts/destinations'
    | '/console/alerts/new'
    | '/console/issues/$issueId'
    | '/console/projects/$projectId'
    | '/console/projects/new'
    | '/console/releases/$version'
    | '/console/reviews/$reviewId'
    | '/console/settings/account'
    | '/console/settings/api-keys'
    | '/console/settings/general'
    | '/console/settings/github'
    | '/console/settings/members'
    | '/console/traces/$traceId'
    | '/console/triage/$bucket'
    | '/console/alerts/'
    | '/console/projects/'
    | '/console/settings/'
    | '/console/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/$'
    | '/api/health'
    | '/api/monitor'
    | '/console/$section'
    | '/console/codebase-map'
    | '/console/live-logs'
    | '/console/overview'
    | '/console/pull-requests'
    | '/console/repositories'
    | '/console/review-rules'
    | '/console/saved-queries'
    | '/console/services'
    | '/otlp/$'
    | '/v1/$'
    | '/webhooks/$'
    | '/console'
    | '/api/auth/$'
    | '/console/alerts/$ruleId'
    | '/console/alerts/activity'
    | '/console/alerts/destinations'
    | '/console/alerts/new'
    | '/console/issues/$issueId'
    | '/console/projects/$projectId'
    | '/console/projects/new'
    | '/console/releases/$version'
    | '/console/reviews/$reviewId'
    | '/console/settings/account'
    | '/console/settings/api-keys'
    | '/console/settings/general'
    | '/console/settings/github'
    | '/console/settings/members'
    | '/console/traces/$traceId'
    | '/console/triage/$bucket'
    | '/console/alerts'
    | '/console/projects'
    | '/console/settings'
    | '/console/traces'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/sign-in'
    | '/api/$'
    | '/api/health'
    | '/api/monitor'
    | '/console/$section'
    | '/console/codebase-map'
    | '/console/live-logs'
    | '/console/overview'
    | '/console/pull-requests'
    | '/console/repositories'
    | '/console/review-rules'
    | '/console/saved-queries'
    | '/console/services'
    | '/console/settings'
    | '/otlp/$'
    | '/v1/$'
    | '/webhooks/$'
    | '/console/'
    | '/api/auth/$'
    | '/console/alerts/$ruleId'
    | '/console/alerts/activity'
    | '/console/alerts/destinations'
    | '/console/alerts/new'
    | '/console/issues/$issueId'
    | '/console/projects/$projectId'
    | '/console/projects/new'
    | '/console/releases/$version'
    | '/console/reviews/$reviewId'
    | '/console/settings/account'
    | '/console/settings/api-keys'
    | '/console/settings/general'
    | '/console/settings/github'
    | '/console/settings/members'
    | '/console/traces/$traceId'
    | '/console/triage/$bucket'
    | '/console/alerts/'
    | '/console/projects/'
    | '/console/settings/'
    | '/console/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMonitorRoute: typeof ApiMonitorRoute
  OtlpSplatRoute: typeof OtlpSplatRoute
  V1SplatRoute: typeof V1SplatRoute
  WebhooksSplatRoute: typeof WebhooksSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitor': {
      id: '/api/monitor'
      path: '/api/monitor'
      fullPath: '/api/monitor'
      preLoaderRoute: typeof ApiMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/$section': {
      id: '/console/$section'
      path: '/$section'
      fullPath: '/console/$section'
      preLoaderRoute: typeof ConsoleSectionRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/codebase-map': {
      id: '/console/codebase-map'
      path: '/codebase-map'
      fullPath: '/console/codebase-map'
      preLoaderRoute: typeof ConsoleCodebaseMapRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/live-logs': {
      id: '/console/live-logs'
      path: '/live-logs'
      fullPath: '/console/live-logs'
      preLoaderRoute: typeof ConsoleLiveLogsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/overview': {
      id: '/console/overview'
      path: '/overview'
      fullPath: '/console/overview'
      preLoaderRoute: typeof ConsoleOverviewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/pull-requests': {
      id: '/console/pull-requests'
      path: '/pull-requests'
      fullPath: '/console/pull-requests'
      preLoaderRoute: typeof ConsolePullRequestsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/repositories': {
      id: '/console/repositories'
      path: '/repositories'
      fullPath: '/console/repositories'
      preLoaderRoute: typeof ConsoleRepositoriesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/review-rules': {
      id: '/console/review-rules'
      path: '/review-rules'
      fullPath: '/console/review-rules'
      preLoaderRoute: typeof ConsoleReviewRulesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/saved-queries': {
      id: '/console/saved-queries'
      path: '/saved-queries'
      fullPath: '/console/saved-queries'
      preLoaderRoute: typeof ConsoleSavedQueriesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/services': {
      id: '/console/services'
      path: '/services'
      fullPath: '/console/services'
      preLoaderRoute: typeof ConsoleServicesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/otlp/$': {
      id: '/otlp/$'
      path: '/otlp/$'
      fullPath: '/otlp/$'
      preLoaderRoute: typeof OtlpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/$': {
      id: '/webhooks/$'
      path: '/webhooks/$'
      fullPath: '/webhooks/$'
      preLoaderRoute: typeof WebhooksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/alerts/': {
      id: '/console/alerts/'
      path: '/alerts'
      fullPath: '/console/alerts/'
      preLoaderRoute: typeof ConsoleAlertsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/alerts/$ruleId': {
      id: '/console/alerts/$ruleId'
      path: '/alerts/$ruleId'
      fullPath: '/console/alerts/$ruleId'
      preLoaderRoute: typeof ConsoleAlertsRuleIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/alerts/activity': {
      id: '/console/alerts/activity'
      path: '/alerts/activity'
      fullPath: '/console/alerts/activity'
      preLoaderRoute: typeof ConsoleAlertsActivityRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/alerts/destinations': {
      id: '/console/alerts/destinations'
      path: '/alerts/destinations'
      fullPath: '/console/alerts/destinations'
      preLoaderRoute: typeof ConsoleAlertsDestinationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/alerts/new': {
      id: '/console/alerts/new'
      path: '/alerts/new'
      fullPath: '/console/alerts/new'
      preLoaderRoute: typeof ConsoleAlertsNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/issues/$issueId': {
      id: '/console/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/console/issues/$issueId'
      preLoaderRoute: typeof ConsoleIssuesIssueIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/projects/': {
      id: '/console/projects/'
      path: '/projects'
      fullPath: '/console/projects/'
      preLoaderRoute: typeof ConsoleProjectsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/projects/$projectId': {
      id: '/console/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/console/projects/$projectId'
      preLoaderRoute: typeof ConsoleProjectsProjectIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/projects/new': {
      id: '/console/projects/new'
      path: '/projects/new'
      fullPath: '/console/projects/new'
      preLoaderRoute: typeof ConsoleProjectsNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/releases/$version': {
      id: '/console/releases/$version'
      path: '/releases/$version'
      fullPath: '/console/releases/$version'
      preLoaderRoute: typeof ConsoleReleasesVersionRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/reviews/$reviewId': {
      id: '/console/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/console/reviews/$reviewId'
      preLoaderRoute: typeof ConsoleReviewsReviewIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/': {
      id: '/console/settings/'
      path: '/'
      fullPath: '/console/settings/'
      preLoaderRoute: typeof ConsoleSettingsIndexRouteImport
      parentRoute: typeof ConsoleSettingsRoute
    }
    '/console/settings/account': {
      id: '/console/settings/account'
      path: '/account'
      fullPath: '/console/settings/account'
      preLoaderRoute: typeof ConsoleSettingsAccountRouteImport
      parentRoute: typeof ConsoleSettingsRoute
    }
    '/console/settings/api-keys': {
      id: '/console/settings/api-keys'
      path: '/api-keys'
      fullPath: '/console/settings/api-keys'
      preLoaderRoute: typeof ConsoleSettingsApiKeysRouteImport
      parentRoute: typeof ConsoleSettingsRoute
    }
    '/console/settings/general': {
      id: '/console/settings/general'
      path: '/general'
      fullPath: '/console/settings/general'
      preLoaderRoute: typeof ConsoleSettingsGeneralRouteImport
      parentRoute: typeof ConsoleSettingsRoute
    }
    '/console/settings/github': {
      id: '/console/settings/github'
      path: '/github'
      fullPath: '/console/settings/github'
      preLoaderRoute: typeof ConsoleSettingsGithubRouteImport
      parentRoute: typeof ConsoleSettingsRoute
    }
    '/console/settings/members': {
      id: '/console/settings/members'
      path: '/members'
      fullPath: '/console/settings/members'
      preLoaderRoute: typeof ConsoleSettingsMembersRouteImport
      parentRoute: typeof ConsoleSettingsRoute
    }
    '/console/traces/': {
      id: '/console/traces/'
      path: '/traces'
      fullPath: '/console/traces/'
      preLoaderRoute: typeof ConsoleTracesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/traces/$traceId': {
      id: '/console/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/console/traces/$traceId'
      preLoaderRoute: typeof ConsoleTracesTraceIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/triage/$bucket': {
      id: '/console/triage/$bucket'
      path: '/triage/$bucket'
      fullPath: '/console/triage/$bucket'
      preLoaderRoute: typeof ConsoleTriageBucketRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleSettingsRouteChildren {
  ConsoleSettingsAccountRoute: typeof ConsoleSettingsAccountRoute
  ConsoleSettingsApiKeysRoute: typeof ConsoleSettingsApiKeysRoute
  ConsoleSettingsGeneralRoute: typeof ConsoleSettingsGeneralRoute
  ConsoleSettingsGithubRoute: typeof ConsoleSettingsGithubRoute
  ConsoleSettingsMembersRoute: typeof ConsoleSettingsMembersRoute
  ConsoleSettingsIndexRoute: typeof ConsoleSettingsIndexRoute
}

const ConsoleSettingsRouteChildren: ConsoleSettingsRouteChildren = {
  ConsoleSettingsAccountRoute: ConsoleSettingsAccountRoute,
  ConsoleSettingsApiKeysRoute: ConsoleSettingsApiKeysRoute,
  ConsoleSettingsGeneralRoute: ConsoleSettingsGeneralRoute,
  ConsoleSettingsGithubRoute: ConsoleSettingsGithubRoute,
  ConsoleSettingsMembersRoute: ConsoleSettingsMembersRoute,
  ConsoleSettingsIndexRoute: ConsoleSettingsIndexRoute,
}

const ConsoleSettingsRouteWithChildren = ConsoleSettingsRoute._addFileChildren(
  ConsoleSettingsRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleSectionRoute: typeof ConsoleSectionRoute
  ConsoleCodebaseMapRoute: typeof ConsoleCodebaseMapRoute
  ConsoleLiveLogsRoute: typeof ConsoleLiveLogsRoute
  ConsoleOverviewRoute: typeof ConsoleOverviewRoute
  ConsolePullRequestsRoute: typeof ConsolePullRequestsRoute
  ConsoleRepositoriesRoute: typeof ConsoleRepositoriesRoute
  ConsoleReviewRulesRoute: typeof ConsoleReviewRulesRoute
  ConsoleSavedQueriesRoute: typeof ConsoleSavedQueriesRoute
  ConsoleServicesRoute: typeof ConsoleServicesRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRouteWithChildren
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleAlertsRuleIdRoute: typeof ConsoleAlertsRuleIdRoute
  ConsoleAlertsActivityRoute: typeof ConsoleAlertsActivityRoute
  ConsoleAlertsDestinationsRoute: typeof ConsoleAlertsDestinationsRoute
  ConsoleAlertsNewRoute: typeof ConsoleAlertsNewRoute
  ConsoleIssuesIssueIdRoute: typeof ConsoleIssuesIssueIdRoute
  ConsoleProjectsProjectIdRoute: typeof ConsoleProjectsProjectIdRoute
  ConsoleProjectsNewRoute: typeof ConsoleProjectsNewRoute
  ConsoleReleasesVersionRoute: typeof ConsoleReleasesVersionRoute
  ConsoleReviewsReviewIdRoute: typeof ConsoleReviewsReviewIdRoute
  ConsoleTracesTraceIdRoute: typeof ConsoleTracesTraceIdRoute
  ConsoleTriageBucketRoute: typeof ConsoleTriageBucketRoute
  ConsoleAlertsIndexRoute: typeof ConsoleAlertsIndexRoute
  ConsoleProjectsIndexRoute: typeof ConsoleProjectsIndexRoute
  ConsoleTracesIndexRoute: typeof ConsoleTracesIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleSectionRoute: ConsoleSectionRoute,
  ConsoleCodebaseMapRoute: ConsoleCodebaseMapRoute,
  ConsoleLiveLogsRoute: ConsoleLiveLogsRoute,
  ConsoleOverviewRoute: ConsoleOverviewRoute,
  ConsolePullRequestsRoute: ConsolePullRequestsRoute,
  ConsoleRepositoriesRoute: ConsoleRepositoriesRoute,
  ConsoleReviewRulesRoute: ConsoleReviewRulesRoute,
  ConsoleSavedQueriesRoute: ConsoleSavedQueriesRoute,
  ConsoleServicesRoute: ConsoleServicesRoute,
  ConsoleSettingsRoute: ConsoleSettingsRouteWithChildren,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleAlertsRuleIdRoute: ConsoleAlertsRuleIdRoute,
  ConsoleAlertsActivityRoute: ConsoleAlertsActivityRoute,
  ConsoleAlertsDestinationsRoute: ConsoleAlertsDestinationsRoute,
  ConsoleAlertsNewRoute: ConsoleAlertsNewRoute,
  ConsoleIssuesIssueIdRoute: ConsoleIssuesIssueIdRoute,
  ConsoleProjectsProjectIdRoute: ConsoleProjectsProjectIdRoute,
  ConsoleProjectsNewRoute: ConsoleProjectsNewRoute,
  ConsoleReleasesVersionRoute: ConsoleReleasesVersionRoute,
  ConsoleReviewsReviewIdRoute: ConsoleReviewsReviewIdRoute,
  ConsoleTracesTraceIdRoute: ConsoleTracesTraceIdRoute,
  ConsoleTriageBucketRoute: ConsoleTriageBucketRoute,
  ConsoleAlertsIndexRoute: ConsoleAlertsIndexRoute,
  ConsoleProjectsIndexRoute: ConsoleProjectsIndexRoute,
  ConsoleTracesIndexRoute: ConsoleTracesIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMonitorRoute: ApiMonitorRoute,
  OtlpSplatRoute: OtlpSplatRoute,
  V1SplatRoute: V1SplatRoute,
  WebhooksSplatRoute: WebhooksSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
