import {
  IconBrandCSharp,
  IconBrandGolang,
  IconBrandJavascript,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandPhp,
  IconBrandPython,
  IconBrandReact,
  IconBrandSentry,
  IconBroadcast,
  IconCoffee,
  IconDiamond,
} from '@tabler/icons-react'
import type { Platform } from './types'

const npm = (pkg: string) => ({ label: 'Install', code: `npm install ${pkg}` })

export const PLATFORMS: Platform[] = [
  {
    id: 'node',
    label: 'Node.js',
    group: 'JavaScript',
    icon: IconBrandNodejs,
    badge: 'JS',
    keywords: 'node express fastify nest server',
    envName: 'SENTRY_DSN',
    install: npm('@sentry/node'),
  },
  {
    id: 'bun',
    label: 'Bun',
    group: 'JavaScript',
    icon: null,
    badge: 'Bun',
    keywords: 'bun elysia hono server',
    envName: 'SENTRY_DSN',
    install: { label: 'Install', code: 'bun add @sentry/bun' },
  },
  {
    id: 'browser',
    label: 'Browser JavaScript',
    group: 'JavaScript',
    icon: IconBrandJavascript,
    badge: 'JS',
    keywords: 'browser vanilla vue svelte frontend web',
    envName: 'VITE_SENTRY_DSN',
    install: npm('@sentry/browser'),
  },
  {
    id: 'react',
    label: 'React',
    group: 'JavaScript',
    icon: IconBrandReact,
    badge: 'RE',
    keywords: 'react vite spa frontend',
    envName: 'VITE_SENTRY_DSN',
    install: npm('@sentry/react'),
  },
  {
    id: 'nextjs',
    label: 'Next.js',
    group: 'JavaScript',
    icon: IconBrandNextjs,
    badge: 'NX',
    keywords: 'next nextjs vercel react',
    envName: 'NEXT_PUBLIC_SENTRY_DSN',
    install: npm('@sentry/nextjs'),
  },
  {
    id: 'tanstack-start',
    label: 'TanStack Start',
    group: 'JavaScript',
    icon: null,
    badge: 'TS',
    keywords: 'tanstack start router react',
    envName: 'VITE_SENTRY_DSN',
    install: npm('@sentry/tanstackstart-react'),
  },
  {
    id: 'python',
    label: 'Python',
    group: 'Server',
    icon: IconBrandPython,
    badge: 'PY',
    keywords: 'python django flask fastapi',
    envName: 'SENTRY_DSN',
    install: { label: 'Install', code: 'pip install sentry-sdk' },
  },
  {
    id: 'go',
    label: 'Go',
    group: 'Server',
    icon: IconBrandGolang,
    badge: 'GO',
    keywords: 'go golang',
    envName: 'SENTRY_DSN',
    install: { label: 'Install', code: 'go get github.com/getsentry/sentry-go' },
  },
  {
    id: 'ruby',
    label: 'Ruby',
    group: 'Server',
    icon: IconDiamond,
    badge: 'RB',
    keywords: 'ruby rails sinatra',
    envName: 'SENTRY_DSN',
    install: { label: 'Install', code: 'bundle add sentry-ruby' },
  },
  {
    id: 'php',
    label: 'PHP',
    group: 'Server',
    icon: IconBrandPhp,
    badge: 'PHP',
    keywords: 'php laravel symfony',
    envName: 'SENTRY_DSN',
    install: { label: 'Install', code: 'composer require sentry/sentry' },
  },
  {
    id: 'java',
    label: 'Java',
    group: 'Server',
    icon: IconCoffee,
    badge: 'JV',
    keywords: 'java kotlin spring jvm gradle maven',
    envName: 'SENTRY_DSN',
    install: { label: 'Gradle', code: "implementation 'io.sentry:sentry:8.+'" },
  },
  {
    id: 'dotnet',
    label: '.NET',
    group: 'Server',
    icon: IconBrandCSharp,
    badge: 'C#',
    keywords: 'dotnet csharp aspnet',
    envName: 'SENTRY_DSN',
    install: { label: 'Install', code: 'dotnet add package Sentry' },
  },
  {
    id: 'sentry',
    label: 'Other / Sentry-compatible',
    group: 'Anything else',
    icon: IconBrandSentry,
    badge: 'SDK',
    keywords: 'other sentry sdk curl rust elixir swift android',
    envName: 'SENTRY_DSN',
    install: null,
  },
  {
    id: 'otlp',
    label: 'OpenTelemetry (OTLP)',
    group: 'Anything else',
    icon: IconBroadcast,
    badge: 'OT',
    keywords: 'opentelemetry otel otlp logs traces',
    envName: null,
    install: null,
  },
]
